project_id = "fijbvihinhuedkvkxwir"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[edge_runtime]
enabled = true
port = 54325

[functions.analytics-ai]
verify_jwt = false

[functions.facebook-webhook]
verify_jwt = false

[functions.website-chat-ai]
verify_jwt = false

[functions.sync-facebook-catalog]
verify_jwt = false

[functions.send-notification-sms]
verify_jwt = false

[functions.create-backup]
verify_jwt = false

[functions.test-openai]
verify_jwt = false

[functions.test-facebook]
verify_jwt = false

[functions.sync-ai-secrets]
verify_jwt = false

[functions.test-facebook-webhook]
verify_jwt = false

[functions.sync-meta-token]
verify_jwt = false

[functions.debug-facebook-messaging]
verify_jwt = false

[functions.test-facebook-send]
verify_jwt = false

[functions.instagram-webhook]
verify_jwt = false

[functions.notify-admin-purchase]
verify_jwt = false

[functions.test-admin-notification]
verify_jwt = false